// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: EventService.proto

package internalgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	EventTime     string                 `protobuf:"bytes,3,opt,name=EventTime,proto3" json:"EventTime,omitempty"`
	Duration      int64                  `protobuf:"varint,4,opt,name=Duration,proto3" json:"Duration,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=Description,proto3" json:"Description,omitempty"`
	UserID        int64                  `protobuf:"varint,6,opt,name=UserID,proto3" json:"UserID,omitempty"`
	TimeToNotify  string                 `protobuf:"bytes,7,opt,name=TimeToNotify,proto3" json:"TimeToNotify,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_EventService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_EventService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_EventService_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetEventTime() string {
	if x != nil {
		return x.EventTime
	}
	return ""
}

func (x *Event) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Event) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *Event) GetTimeToNotify() string {
	if x != nil {
		return x.TimeToNotify
	}
	return ""
}

type RequestCreateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	UserID        int64                  `protobuf:"varint,3,opt,name=UserID,proto3" json:"UserID,omitempty"`
	TimeToNotify  string                 `protobuf:"bytes,4,opt,name=TimeToNotify,proto3" json:"TimeToNotify,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestCreateEvent) Reset() {
	*x = RequestCreateEvent{}
	mi := &file_EventService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestCreateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCreateEvent) ProtoMessage() {}

func (x *RequestCreateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_EventService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCreateEvent.ProtoReflect.Descriptor instead.
func (*RequestCreateEvent) Descriptor() ([]byte, []int) {
	return file_EventService_proto_rawDescGZIP(), []int{1}
}

func (x *RequestCreateEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RequestCreateEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RequestCreateEvent) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *RequestCreateEvent) GetTimeToNotify() string {
	if x != nil {
		return x.TimeToNotify
	}
	return ""
}

type RequestGetEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestGetEvent) Reset() {
	*x = RequestGetEvent{}
	mi := &file_EventService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGetEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGetEvent) ProtoMessage() {}

func (x *RequestGetEvent) ProtoReflect() protoreflect.Message {
	mi := &file_EventService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGetEvent.ProtoReflect.Descriptor instead.
func (*RequestGetEvent) Descriptor() ([]byte, []int) {
	return file_EventService_proto_rawDescGZIP(), []int{2}
}

func (x *RequestGetEvent) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type RequestUpdateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	UserID        int64                  `protobuf:"varint,4,opt,name=UserID,proto3" json:"UserID,omitempty"`
	TimeToNotify  string                 `protobuf:"bytes,5,opt,name=TimeToNotify,proto3" json:"TimeToNotify,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestUpdateEvent) Reset() {
	*x = RequestUpdateEvent{}
	mi := &file_EventService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUpdateEvent) ProtoMessage() {}

func (x *RequestUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_EventService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUpdateEvent.ProtoReflect.Descriptor instead.
func (*RequestUpdateEvent) Descriptor() ([]byte, []int) {
	return file_EventService_proto_rawDescGZIP(), []int{3}
}

func (x *RequestUpdateEvent) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *RequestUpdateEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RequestUpdateEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RequestUpdateEvent) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *RequestUpdateEvent) GetTimeToNotify() string {
	if x != nil {
		return x.TimeToNotify
	}
	return ""
}

type RequestDeleteEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestDeleteEvent) Reset() {
	*x = RequestDeleteEvent{}
	mi := &file_EventService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestDeleteEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDeleteEvent) ProtoMessage() {}

func (x *RequestDeleteEvent) ProtoReflect() protoreflect.Message {
	mi := &file_EventService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDeleteEvent.ProtoReflect.Descriptor instead.
func (*RequestDeleteEvent) Descriptor() ([]byte, []int) {
	return file_EventService_proto_rawDescGZIP(), []int{4}
}

func (x *RequestDeleteEvent) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type RequestListByDate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DateTme       string                 `protobuf:"bytes,1,opt,name=DateTme,proto3" json:"DateTme,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestListByDate) Reset() {
	*x = RequestListByDate{}
	mi := &file_EventService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestListByDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestListByDate) ProtoMessage() {}

func (x *RequestListByDate) ProtoReflect() protoreflect.Message {
	mi := &file_EventService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestListByDate.ProtoReflect.Descriptor instead.
func (*RequestListByDate) Descriptor() ([]byte, []int) {
	return file_EventService_proto_rawDescGZIP(), []int{5}
}

func (x *RequestListByDate) GetDateTme() string {
	if x != nil {
		return x.DateTme
	}
	return ""
}

type ResponseListByDate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=Events,proto3" json:"Events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseListByDate) Reset() {
	*x = ResponseListByDate{}
	mi := &file_EventService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseListByDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseListByDate) ProtoMessage() {}

func (x *ResponseListByDate) ProtoReflect() protoreflect.Message {
	mi := &file_EventService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseListByDate.ProtoReflect.Descriptor instead.
func (*ResponseListByDate) Descriptor() ([]byte, []int) {
	return file_EventService_proto_rawDescGZIP(), []int{6}
}

func (x *ResponseListByDate) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_EventService_proto protoreflect.FileDescriptor

const file_EventService_proto_rawDesc = "" +
	"\n" +
	"\x12EventService.proto\x12\x05event\"\xc5\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x14\n" +
	"\x05Title\x18\x02 \x01(\tR\x05Title\x12\x1c\n" +
	"\tEventTime\x18\x03 \x01(\tR\tEventTime\x12\x1a\n" +
	"\bDuration\x18\x04 \x01(\x03R\bDuration\x12 \n" +
	"\vDescription\x18\x05 \x01(\tR\vDescription\x12\x16\n" +
	"\x06UserID\x18\x06 \x01(\x03R\x06UserID\x12\"\n" +
	"\fTimeToNotify\x18\a \x01(\tR\fTimeToNotify\"\x88\x01\n" +
	"\x12RequestCreateEvent\x12\x14\n" +
	"\x05Title\x18\x01 \x01(\tR\x05Title\x12 \n" +
	"\vDescription\x18\x02 \x01(\tR\vDescription\x12\x16\n" +
	"\x06UserID\x18\x03 \x01(\x03R\x06UserID\x12\"\n" +
	"\fTimeToNotify\x18\x04 \x01(\tR\fTimeToNotify\"!\n" +
	"\x0fRequestGetEvent\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\"\x98\x01\n" +
	"\x12RequestUpdateEvent\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x14\n" +
	"\x05Title\x18\x02 \x01(\tR\x05Title\x12 \n" +
	"\vDescription\x18\x03 \x01(\tR\vDescription\x12\x16\n" +
	"\x06UserID\x18\x04 \x01(\x03R\x06UserID\x12\"\n" +
	"\fTimeToNotify\x18\x05 \x01(\tR\fTimeToNotify\"$\n" +
	"\x12RequestDeleteEvent\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\"-\n" +
	"\x11RequestListByDate\x12\x18\n" +
	"\aDateTme\x18\x01 \x01(\tR\aDateTme\":\n" +
	"\x12ResponseListByDate\x12$\n" +
	"\x06Events\x18\x01 \x03(\v2\f.event.EventR\x06Events2\xb1\x03\n" +
	"\fEventService\x126\n" +
	"\vCreateEvent\x12\x19.event.RequestCreateEvent\x1a\f.event.Event\x120\n" +
	"\bGetEvent\x12\x16.event.RequestGetEvent\x1a\f.event.Event\x126\n" +
	"\vUpdateEvent\x12\x19.event.RequestUpdateEvent\x1a\f.event.Event\x126\n" +
	"\vDeleteEvent\x12\x19.event.RequestDeleteEvent\x1a\f.event.Event\x12@\n" +
	"\tListByDay\x12\x18.event.RequestListByDate\x1a\x19.event.ResponseListByDate\x12A\n" +
	"\n" +
	"ListByWeek\x12\x18.event.RequestListByDate\x1a\x19.event.ResponseListByDate\x12B\n" +
	"\vListByMonth\x12\x18.event.RequestListByDate\x1a\x19.event.ResponseListByDateB\x11Z\x0f./;internalgrpcb\x06proto3"

var (
	file_EventService_proto_rawDescOnce sync.Once
	file_EventService_proto_rawDescData []byte
)

func file_EventService_proto_rawDescGZIP() []byte {
	file_EventService_proto_rawDescOnce.Do(func() {
		file_EventService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_EventService_proto_rawDesc), len(file_EventService_proto_rawDesc)))
	})
	return file_EventService_proto_rawDescData
}

var file_EventService_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_EventService_proto_goTypes = []any{
	(*Event)(nil),              // 0: event.Event
	(*RequestCreateEvent)(nil), // 1: event.RequestCreateEvent
	(*RequestGetEvent)(nil),    // 2: event.RequestGetEvent
	(*RequestUpdateEvent)(nil), // 3: event.RequestUpdateEvent
	(*RequestDeleteEvent)(nil), // 4: event.RequestDeleteEvent
	(*RequestListByDate)(nil),  // 5: event.RequestListByDate
	(*ResponseListByDate)(nil), // 6: event.ResponseListByDate
}
var file_EventService_proto_depIdxs = []int32{
	0, // 0: event.ResponseListByDate.Events:type_name -> event.Event
	1, // 1: event.EventService.CreateEvent:input_type -> event.RequestCreateEvent
	2, // 2: event.EventService.GetEvent:input_type -> event.RequestGetEvent
	3, // 3: event.EventService.UpdateEvent:input_type -> event.RequestUpdateEvent
	4, // 4: event.EventService.DeleteEvent:input_type -> event.RequestDeleteEvent
	5, // 5: event.EventService.ListByDay:input_type -> event.RequestListByDate
	5, // 6: event.EventService.ListByWeek:input_type -> event.RequestListByDate
	5, // 7: event.EventService.ListByMonth:input_type -> event.RequestListByDate
	0, // 8: event.EventService.CreateEvent:output_type -> event.Event
	0, // 9: event.EventService.GetEvent:output_type -> event.Event
	0, // 10: event.EventService.UpdateEvent:output_type -> event.Event
	0, // 11: event.EventService.DeleteEvent:output_type -> event.Event
	6, // 12: event.EventService.ListByDay:output_type -> event.ResponseListByDate
	6, // 13: event.EventService.ListByWeek:output_type -> event.ResponseListByDate
	6, // 14: event.EventService.ListByMonth:output_type -> event.ResponseListByDate
	8, // [8:15] is the sub-list for method output_type
	1, // [1:8] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_EventService_proto_init() }
func file_EventService_proto_init() {
	if File_EventService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_EventService_proto_rawDesc), len(file_EventService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_EventService_proto_goTypes,
		DependencyIndexes: file_EventService_proto_depIdxs,
		MessageInfos:      file_EventService_proto_msgTypes,
	}.Build()
	File_EventService_proto = out.File
	file_EventService_proto_goTypes = nil
	file_EventService_proto_depIdxs = nil
}
