Server:
  Host:
  Port: 8082
  AddressGrpc: ":50051"
  IsHTTP: true

Logger:
  Level: DEBUG
  File: test.txt

DB:
  Host: localhost
  Port: 5432
  Username: user
  Password: password
  DBName: otus
  InMemory: false